name: Update App Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'versionName (e.g. 2024.3.1)'     
        required: true
        default: '2024.3.1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update App Version
        uses: mikefarah/yq@master
        with:
          cmd: APP_VERSION=${{ github.event.inputs.version }} yq eval '.env.APP_VERSION = env(APP_VERSION)' -i ${{ github.workspace }}/.github/workflows/android.yml
